### ISSUE TITLE
Future suggested options !

### ISSUE THREAD

**Issue by prodnet** [walleth/KHardWareWallet#5]
Future suggested options:

* plausible deniability
* implement SLIP-0039 or Shamir secret sharing (iancoleman.io)
* auto completion of recovery mnemonic seed, after N chars
* integration of all major cryptocurrencies, Ethereum and ERC20 tokens, Bitcoin, Bitcoin Cash, Litecoin, Ripple, ...etc.
* lock application with a password
* auto-delete after N wrong passwords

I hope these suggestions will motivate you to greatly improve this application.
Thanks.

**Comment by ligi** [comment]
this is the wrong repo for this. these changes must be done in the javacard software
